version: "3.8"

services:
  preview:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: nexa-ui-preview
    restart: unless-stopped

  docs:
    build:
      context: .
      dockerfile: Dockerfile.docs
    ports:
      - "3001:80"
    container_name: nexa-ui-docs
    restart: unless-stopped
