version: "3.8"

services:
  nexa-ui-preview:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexa-ui-preview
    command: npm run dev -- --host 0.0.0.0 --port 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  nexa-ui-docs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexa-ui-docs
    command: npm run docs:dev -- --host 0.0.0.0 --port 3001
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
