server {
    listen 3000;
    server_name localhost;
    root /usr/share/nginx/html/components;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 3001;
    server_name localhost;
    root /usr/share/nginx/html/docs;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
